@baseUrl = http://localhost:3000/api

#Categories

# @name getAllCategories
GET {{ baseUrl }}/categories

###

# @name addNewCategories
POST {{ baseUrl }}/categories
content-type: application/json

{
    "name": "Laptop"
}

###

# @name updateCategories
PATCH {{ baseUrl }}/categories/2
content-type: application/json

{
    "name": " New Laptop"
}

###

# @name deleteCategories
DELETE {{ baseUrl }}/categories/2